import Head from 'next/head'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <nav>Navbar with logo, search bar and profile.</nav>
        <h1>Show a list of recently published newsletters from different interest fields.</h1>
      </main>
    </>
  )
}
